GET http://localhost:5054

GET http://localhost:5054/games

GET http://localhost:5054/games/11

POST http://localhost:5054/games
 Content-Type: application/json

 {
     "name" : "Grand Theft Auto V",
     "genre" : "Action - Adventure",
     "price" : 29.99,
     "releaseDate" : "2015-05-05"
 }

PUT http://localhost:5054/games/11
Content-Type: application/json

{
    "name" : "Grand Theft Auto VI",
     "genre" : "Action - Adventure",
     "price" : 99.99,
     "releaseDate" : "2026-05-05"
}

DELETE http://localhost:5054/games/11