GET http://localhost:5054/games

GET http://localhost:5054/games/8

POST http://localhost:5054/games
 Content-Type: application/json

 {
     "name" : "Hollow Knight",
     "genreId" : 6,
     "price" : 49.99,
     "releaseDate": "2017-02-24"
 }

PUT http://localhost:5054/games/3
Content-Type: application/json

{
  "name": "The Witcher 3: Wild Hunt",
     // "genre" : "Action - Adventure",
     "genreId" : 3,
     "price" : 19.99,
     "releaseDate" : "2015-05-08"
}

DELETE http://localhost:5054/games/8